<a href="https://colab.research.google.com/github/jacobhjh0999/inflearn_Numpy_Basic_for_ds/blob/main/1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
#Section1. N차원 배열(ndarray 생성)
### N차원 배열을 생성하는 여러가지 방법, 데이터타입, 간단하게 데이터를 시각화하는 방법을 다룬다.
---

In [ ]:
import numpy as np

## ✅ `np.array()`는 `리스트, 튜플을 받아서` `배열`을 만든다

np.array()는 리스트를 NumPy 배열(ndarray)로 변환하는 역할을 해.

In [ ]:
# 리스트를 배열(ndarray)로
my_list = [1,2,3,4]
arr_by_list = np.array(my_list)
print(arr_by_list)

[1 2 3 4]


In [ ]:
# 튜플을 배열(ndarray)로
my_tuple = (1,2,3,4)
arr_by_tuple = np.array(my_tuple)
print(arr_by_tuple)

[1 2 3 4]


## ✅ 1. 리스트와 배열의 기본 개념

| 특징 | Python 리스트 (`list`) | NumPy 배열 (`np.array`) |
|------|--------------------|--------------------|
| **데이터 저장 방식** | 객체의 모음 (다양한 타입 가능) | 동일한 타입의 값이 연속적으로 저장됨 |
| **연산 방식** | 반복문을 사용해야 연산 가능 | 벡터 연산 가능 (빠름) |
| **속도** | 상대적으로 느림 | 빠름 |
| **메모리 사용** | 추가적인 메타데이터 포함 | 연속된 메모리 블록 사용 (더 효율적) |


In [ ]:
# 리스트
list = [1,2,3]
print(type(list))
print(list)


# ndarray
arr = np.array([1,2,3])
print(type(arr))
print(arr)

<class 'list'>
[1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3]


## 🧐 ndarray란?

`ndarray`는 **"N-dimensional array"**의 줄임말이야.

- **`nd`** → *N-dimensional (N차원)*
- **`array`** → *배열*

즉, `ndarray`는 **N차원(다차원) 배열**을 의미하는 NumPy의 기본 데이터 구조야.  
NumPy에서 배열을 만들면 내부적으로 `ndarray` 객체가 생성되는데,  
1차원, 2차원, 3차원 이상도 모두 `ndarray`로 표현할 수 있어!


In [ ]:
# 1차원 배열
arr1 = np.array([1,2,3])
print(arr1)
# 2차원 배열
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


괄호...
## 💡 attribute와 method 차이

- **attribute**는 데이터를 **저장하거나 표시하는 속성**이고, `shape`처럼 **읽기 전용**일 수 있어.
- **method**는 객체에 **동작을 수행하는 함수**인데, 예를 들어 `arr.sum()`은 배열의 합을 구하는 **method**야.

### 예시
- **attribute**: `arr.shape`, `arr.size`, `arr.dtype` 등
- **method**: `arr.sum()`, `arr.mean()`, `arr.reshape()` 등


In [ ]:
# shape (괄호 안침 주의!!!)
print(arr1.shape , arr2.shape)

# ndim
print(arr1.ndim , arr2.ndim)

# size
print(arr1.size , arr2.size)

(3,) (3, 3)
1 2
3 9


---
## Section 1-2. N차원 배열의 데이터 타입

- numpy의 ndarray에는 list와 달리 **하나의 데이터타입만** 저장할 수 있다.

In [13]:
import numpy as np
# 데이터타입이 혼재하는 경우
arr= np.array([1,1.6,2.3,6.7])
print(arr,arr.dtype)

[1.  1.6 2.3 6.7] float64


In [16]:
arr= np.array([0,1.6,2.3,6.7],dtype=bool)
print(arr,arr.dtype)
arr=arr.astype(float)  #넣어줘야함.
print(arr,arr.dtype)

[False  True  True  True] bool
[0. 1. 1. 1.] float64


---
## Section 1-3. 정해진 형식의 N차원 배열 생성하기

-

In [17]:
# np.zeros() => 모든 요소가 0인 행렬(배열)
arr = np.zeros([2,2]) # 2*2 => shape을 전달
print(arr)

[[0. 0.]
 [0. 0.]]


In [24]:
# np.ones() => 모든 요소가 1인 행렬
arr = np.ones([3,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# np.full() => 원하는 것으로 행렬을 채우기
arr = np.full([2,3],5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [27]:
# np.eye() => 대각 요소가 1
arr = np.eye(3,4,k=1) #k는 대각요소의 시작지점
print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
#Section2. N차원 배열 인덱싱
### 배열의 index를 이용해 값에 접근하는 방법과 특정 범위의 값들을 탐색하는 방법을 배운다.
---

---
#Section3. N차원 배열의 연산법
### 행렬의 사칙연산, 내적연산, 비교연산 등 기본적인 연산법과 브로드캐스팅 연산 과정을 배운다.
---

---
#Section4. N차원 배열 정렬
### 배열의 원소들을 대소관계에 따라 정렬하는 방법을 다룬다.
---

---
#Section5. N차원 배열의 형태 변경
### 배열의 shape를 변형하고 차원을 확장, 축소하는 방법을 다룬다.
---

---
#Section6. N차원 배열의 병합
### 배열의 원소를 추가하고 삭제하는 방법과 데이터를 병합하고 분할하는 방법을 다룬다.
---

---
#Section7. 실습예제

---