<a href="https://colab.research.google.com/github/jacobhjh0999/inflearn_Numpy_Basic_for_ds/blob/main/3_N%EC%B0%A8%EC%9B%90%EB%B0%B0%EC%97%B4%EC%97%B0%EC%82%B0%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
#Section1. N차원 배열(ndarray 생성)
### N차원 배열을 생성하는 여러가지 방법, 데이터타입, 간단하게 데이터를 시각화하는 방법을 다룬다.
---

---
#Section2. N차원 배열 인덱싱
### 배열의 index를 이용해 값에 접근하는 방법과 특정 범위의 값들을 탐색하는 방법을 배운다.
---

---
#Section3. N차원 배열의 연산법
### 행렬의 사칙연산, 내적연산, 비교연산 등 기본적인 연산법과 브로드캐스팅 연산 과정을 배운다.
---

---
## 3-1. 배열의 연산 1: 사칙연산/제곱/제곱근/몫/나머지

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6,],
                 [7,8,9]])
arr2 = np.array([[2,2,2],
                 [2,2,2],
                 [2,2,2]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
# 덧셈
#1
print(arr1+arr2)
#2
print(np.add(arr1,arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# 뺄셈
#1
print(arr1 - arr2)
#2
print(np.subtract(arr1,arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [ ]:
# 곱셈 => 내적연산(dot product) 아님!! 원소간의 곱 연산
#1
print(arr1 * arr2)
#2
print(np.multiply(arr1,arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# 나눗셈
#1
print(arr1/arr2)
#2
print(np.divide(arr1,arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [ ]:
# 제곱
#1
print(arr1 ** 2)
#2
print(np.square(arr1))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# 제곱근
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# 몫
print(arr1 // 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]


In [ ]:
# 나머지
print(arr1 % 2)

[[1 0 1]
 [0 1 0]
 [1 0 1]]


---
## 3-2. 배열의 연산 2: 내적(dot product)/절댓값/올림/내림/반올림/버림

In [ ]:
# 1차원 행렬에서의 내적
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])
print(np.dot(arr1,arr2))

20


In [ ]:
# 2차원 행렬에서의 내적
arr1 = np.array([[1,2],
                 [4,5]])
arr2 = np.array([[1,2],
                 [0,3]])
print(np.dot(arr1,arr2))

[[ 1  8]
 [ 4 23]]


In [ ]:
# 절댓값
arr1 = np.array([[1,-2],
                 [-4,5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [ ]:
# 올림
arr1 = np.array([[1.932,-2.339],
                 [-4.145,5.206]])
print(np.ceil(arr1))

# 내림
print(np.floor(arr1))

# 반올림
print(np.round(arr1))

# 버림
print(np.trunc(arr1))

[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]


---
## 3-3. 배열의 연산 3: min/max/sum/mean/std/cumsum/median

In [ ]:
arr1 = np.array([[1,2,3],
                 [0,1,4]])

In [ ]:
# 최솟값 출력
print(np.min(arr1))

print(arr1.min())
print(arr1.min(axis=0))   # ==> axis 정리필요..
print(arr1.min(axis=1))

0
0
[0 1 3]
[1 0]


---
### - axis 개념
    - axis = 1

        손가락을 구부리고 행들을 잡으며 위에서 아래쪽으로 연산
    - axis = 0

        손가락을 구부리고 열들을 잡으며 왼쪽에서 오른쪽으로 연산
---

In [ ]:
# 최댓값 출력
print(np.max(arr1))

print(arr1.max())
print(arr1.max(axis=0))
print(arr1.max(axis=1))

4
4
[1 2 4]
[3 4]


In [ ]:
arr = np.array([[1,2,3],
                [0,1,4]])

In [ ]:
# 총합
print(np.sum(arr))
print(arr.sum(axis=0))
print(arr.sum(axis=1))

11
[1 3 7]
[6 5]


In [ ]:
# 평균
print(np.mean(arr))
print(arr.mean(axis=0))
print(arr.mean(axis=1))

1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]


In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [0,1,4]])

In [15]:
# 표준편차 값
print(np.std(arr))
print(arr.std(axis=1))
print(arr.std(axis=0))

1.343709624716425
[0.81649658 1.69967317]
[0.5 0.5 0.5]


In [11]:
# 누적합 계산  # cumulative sum
# 1 / 1~2 / 1~3 /
print(np.cumsum(arr))
print(arr.cumsum(axis=1))  # 잘 모르겠음
print(arr.cumsum(axis=0))

[ 1  3  6  6  7 11]
[[1 3 6]
 [0 1 5]]
[[1 2 3]
 [1 3 7]]


In [ ]:
arr = np.array([[1,2,3],
                [0,1,4]])

- median은 ndarray 객체에 메서드로 정의되어 있지 않아서 arr.median(axis=0) 같은 방식은 ❌
- 대신 np.median(arr, axis=0)처럼 numpy 모듈에서 직접 호출해야 함

In [17]:
# 중간값 계산
print(np.median(arr))
#print(arr.median(axis=1))
#print(arr.median(axis=0))
print(np.median(arr,axis=1))
print(np.median(arr,axis=0))

1.5
[2. 1.]
[0.5 1.5 3.5]


---
## 3-4. 배열의 연산 4: 비교 연산 / 삼각 함수

In [22]:
# 비교 연산
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1,0,3],
                 [4,-2,9]])
print(arr1 == arr2)
print(np.array_equal(arr1,arr2))
print(arr1 > arr2)
print(arr1 >= arr2)

[[ True False  True]
 [ True False False]]
False
[[False  True False]
 [False  True False]]
[[ True  True  True]
 [ True  True False]]


In [24]:
# 삼각함수
arr = np.array([[1,2,3],
                 [4,5,6]])

# 각 원소에 sin
print(np.sin(arr))

# 각 원소에 cos
print(np.cos(arr))

# 각 원소에 tan
print(np.tan(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


---
## 3-5. 브로드캐스팅(BroadCasting)

🎯 정리

- 크기가 1인 차원은 자동으로 확장됨.
작은 배열이 큰 배열과 크기가 같아질 때까지 복제된 것처럼 처리됨.
- 불필요한 메모리 복사를 하지 않으므로 연산이 효율적임.
- np.newaxis나 reshape()을 활용해서 명시적으로 크기를 맞출 수도 있음.

확장

- 1 → N으로 확장되는 것은 가능 ✅
- 2 → 3처럼 서로 다른 크기지만 1이 아닌 경우는 확장 불가능 ❌


In [25]:
arr1 = np.array([[0,0,0],
                 [1,1,1],
                 [2,2,2]])
arr2 = np.array([[5,6,7]])

print(arr1+arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [26]:
arr1 = np.array([[1,1,1]])
arr2 = np.array([[0],
                 [1],
                 [2]])
print(arr1+arr2)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


---
## 3-6. 벡터 연산의 장점

In [27]:
import time

In [ ]:
arr = np.arange(9999999)

---
#Section4. N차원 배열 정렬
### 배열의 원소들을 대소관계에 따라 정렬하는 방법을 다룬다.
---

---
#Section5. N차원 배열의 형태 변경
### 배열의 shape를 변형하고 차원을 확장, 축소하는 방법을 다룬다.
---

---
#Section6. N차원 배열의 병합
### 배열의 원소를 추가하고 삭제하는 방법과 데이터를 병합하고 분할하는 방법을 다룬다.
---

---
#Section7. 실습예제

---