<a href="https://colab.research.google.com/github/jacobhjh0999/inflearn_Numpy_Basic_for_ds/blob/main/4_N%EC%B0%A8%EC%9B%90%EB%B0%B0%EC%97%B4%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
#Section4. N차원 배열 정렬
### 배열의 원소들을 대소관계에 따라 정렬하는 방법을 다룬다.
---

### 4-1. 1차원 배열의 정렬

In [ ]:
import numpy as np

## `np.sort(arr)` vs `arr.sort()` 차이점

### 1. `np.sort(arr)`
- 원본 배열을 변경하지 않고 **정렬된 새로운 배열을 반환**한다.

### 2. `arr.sort()`
- 원본 배열을 직접 정렬하여 **반환값이 None**이다.

### 3. 정리

- `np.sort(arr)`: **원본 배열을 변경하지 않고** 정렬된 새로운 배열을 반환  
- `arr.sort()`: **원본 배열을 직접 정렬하며** 반환값이 `None`  

| 함수 | 원본 변경 여부 | 반환 값 |
|------|--------------|---------|
| `np.sort(arr)` | ❌ (변경 없음) | 정렬된 새로운 배열 |
| `arr.sort()` | ✅ (변경됨) | `None` |

**✅ 선택 가이드**  
- **원본 배열을 유지하면서 정렬된 결과가 필요하면** → `np.sort(arr)`  
- **원본 배열 자체를 정렬하고 싶다면** → `arr.sort()`  

In [ ]:
arr = np.random.randint(0,100,10)
print(arr)

# 정렬된 배열을 return (원본 배열은 변하지 않음)
print(np.sort(arr))

# 배열 자체를 정렬함
arr.sort()
print(arr)

[59 66 71 80 37 54 71 39 26 31]
[26 31 37 39 54 59 66 71 71 80]
[26 31 37 39 54 59 66 71 71 80]


❓ NumPy에는 ascending=True가 없나?
- Pandas와 달리, NumPy의 np.sort()와 .sort()에는 ascending 매개변수가 없다.
👉 NumPy에서는 무조건 오름차순 정렬만 제공하므로, 내림차순을 원하면 [::-1]을 사용해야 함.

In [ ]:
# 내림차순 정렬 (원본 유지)
arr = np.random.randint(0,100,10)
print(np.sort(arr))
print(np.sort(arr)[::-1])

[ 2  9 36 43 43 43 54 65 71 78]
[78 71 65 54 43 43 43 36  9  2]


### 4-2. 2차원 배열의 정렬

In [ ]:
arr = np.random.randint(0,15,size=(3,4))
print(arr)

[[ 8 12  5  5]
 [ 4 12 12  9]
 [ 7  7 13 14]]


In [ ]:
print(np.sort(arr)) # default axis=1

[[ 5  5  8 12]
 [ 4  9 12 12]
 [ 7  7 13 14]]


In [ ]:
print(np.sort(arr,axis=0))

[[ 8 12 13 14]
 [ 7 12 12  9]
 [ 4  7  5  5]]


In [ ]:
print(np.sort(arr,axis=None)) # 2차원배열을 1차원배열로 변환하여 정렬

[ 4  5  5  7  7  8  9 12 12 12 13 14]


🔹 argsort() => **"argument sort"**

🔹 배열을 정렬하는 것이 아니라, 정렬된 순서의 인덱스(index)를 반환한다.

In [ ]:
# argsort()
print(arr)
print(np.argsort(arr,axis=1))

[[ 8 12  5  5]
 [ 4 12 12  9]
 [ 7  7 13 14]]
[[2 3 0 1]
 [0 3 1 2]
 [0 1 2 3]]
