<a href="https://colab.research.google.com/github/hajonghyun/Numpy_study_for_ds/blob/main/4_N%EC%B0%A8%EC%9B%90%EB%B0%B0%EC%97%B4%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
#Section4. N차원 배열 정렬
### 배열의 원소들을 대소관계에 따라 정렬하는 방법을 다룬다.
---

### 4-1. 1차원 배열의 정렬

In [ ]:
import numpy as np

## `np.sort(arr)` vs `arr.sort()` 차이점

### 1. `np.sort(arr)`
- 원본 배열을 변경하지 않고 **정렬된 새로운 배열을 반환**한다.

### 2. `arr.sort()`
- 원본 배열을 직접 정렬하여 **반환값이 None**이다.

### 3. 정리

- `np.sort(arr)`: **원본 배열을 변경하지 않고** 정렬된 새로운 배열을 반환  
- `arr.sort()`: **원본 배열을 직접 정렬하며** 반환값이 `None`  

| 함수 | 원본 변경 여부 | 반환 값 |
|------|--------------|---------|
| `np.sort(arr)` | ❌ (변경 없음) | 정렬된 새로운 배열 |
| `arr.sort()` | ✅ (변경됨) | `None` |

**✅ 선택 가이드**  
- **원본 배열을 유지하면서 정렬된 결과가 필요하면** → `np.sort(arr)`  
- **원본 배열 자체를 정렬하고 싶다면** → `arr.sort()`  

In [ ]:
arr = np.random.randint(0,100,10)
print(arr)

# 정렬된 배열을 return (원본 배열은 변하지 않음)
print(np.sort(arr))

# 배열 자체를 정렬함
arr.sort()
print(arr)

[59 66 71 80 37 54 71 39 26 31]
[26 31 37 39 54 59 66 71 71 80]
[26 31 37 39 54 59 66 71 71 80]


❓ NumPy에는 ascending=True가 없나?
- Pandas와 달리, NumPy의 np.sort()와 .sort()에는 ascending 매개변수가 없다.
👉 NumPy에서는 무조건 오름차순 정렬만 제공하므로, 내림차순을 원하면 [::-1]을 사용해야 함.

In [ ]:
# 내림차순 정렬 (원본 유지)
arr = np.random.randint(0,100,10)
print(np.sort(arr))
print(np.sort(arr)[::-1])

[ 2  9 36 43 43 43 54 65 71 78]
[78 71 65 54 43 43 43 36  9  2]


### 4-2. 2차원 배열의 정렬

In [ ]:
arr = np.random.randint(0,15,size=(3,4))
print(arr)

[[ 8 12  5  5]
 [ 4 12 12  9]
 [ 7  7 13 14]]


In [ ]:
print(np.sort(arr)) # default axis=1

[[ 5  5  8 12]
 [ 4  9 12 12]
 [ 7  7 13 14]]


In [ ]:
print(np.sort(arr,axis=0))

[[ 8 12 13 14]
 [ 7 12 12  9]
 [ 4  7  5  5]]


In [ ]:
print(np.sort(arr,axis=None)) # 2차원배열을 1차원배열로 변환하여 정렬

[ 4  5  5  7  7  8  9 12 12 12 13 14]


🔹 argsort() => **"argument sort"**

🔹 배열을 정렬하는 것이 아니라, 정렬된 순서의 인덱스(index)를 반환한다.

In [ ]:
# argsort()
print(arr)
print(np.argsort(arr,axis=1))

[[ 8 12  5  5]
 [ 4 12 12  9]
 [ 7  7 13 14]]
[[2 3 0 1]
 [0 3 1 2]
 [0 1 2 3]]


Q1. 예측 확률이 가장 높은 클래스 찾기 (ArgSort)

"딥러닝 모델이 5개 클래스에 대한 확률을 출력했습니다. 확률 값이 아니라, **확률이 가장 높은 클래스의 인덱스(번호)**를 알고 싶습니다. (보통 argmax를 쓰지만, 여기서는 순서대로 정렬된 인덱스를 구하는 함수를 써보세요.)"

In [7]:
import numpy as np
probs = np.array([0.1, 0.05, 0.7, 0.05, 0.1])

arr2=np.argsort(probs)[::-1]
arr2[0]


np.int64(2)

Q2. 내림차순 정렬 (Descending Sort)

"손실(Loss) 값을 기록한 배열이 있습니다. 손실이 큰 순서대로(내림차순) 정렬해서 보고 싶습니다. NumPy sort는 오름차순만 지원합니다. 어떻게 뒤집어야 할까요?"

In [9]:
loss = np.array([0.5, 0.1, 0.9, 0.3])
np.sort(loss)[::-1]

array([0.9, 0.5, 0.3, 0.1])

Q3. 배치 데이터 정렬 (Axis Sort)

"(3, 4) 크기의 데이터 묶음(Batch)이 있습니다. 데이터 간에는 섞이면 안 되고, 각 데이터(행) 내부에서만 오름차순으로 정렬하고 싶습니다. 어느 축(axis)을 기준으로 정렬해야 할까요?"

In [10]:
batch_data = np.array([
    [3, 1, 2, 4],
    [5, 8, 6, 7],
    [9, 0, 2, 5]
])

np.sort(batch_data,axis=1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 2, 5, 9]])

🥊 Step 3. 실전 응용 문제 풀기 (Mini Quest)
이번에는 딥러닝 평가 지표인 Top-k Accuracy를 구하기 위한 전 단계, **"상위 k개 후보 추리기"**를 구현해 봅시다.

미션: "이 이미지는 고양이(1), 강아지(3), 아니면 사자(9)일까?"

모델이 5장의 이미지에 대해, 각각 10개의 클래스(0~9)일 확률을 예측했습니다. 확률이 가장 높은 **상위 3개의 클래스(Top-3)**를 뽑아주세요.

[요구사항]

데이터 생성:

predictions: (5, 10) 크기의 난수 (0~1 사이 rand 사용)

5명의 유저가 10개의 상품을 구매할 확률이라고 생각해도 좋습니다.

Top-3 추출:

각 행(Row)마다 확률이 가장 높은 **상위 3개의 인덱스(클래스 번호)**를 찾으세요.

주의: 확률이 높은 순서대로 (1등, 2등, 3등) 나와야 합니다.

Q. 결과가 (5, 3) 크기의 인덱스 배열로 나오도록 코드를 작성하세요.

In [23]:
np.random.seed(3)
pred = np.random.rand(5,10)
s_pred = np.argsort(pred,axis=1)[:,::-1]
s_pred[:,0:3]

array([[5, 4, 1],
       [4, 2, 5],
       [9, 5, 1],
       [0, 2, 3],
       [5, 6, 1]])