<a href="https://colab.research.google.com/github/hajonghyun/inflearn_Numpy_Basic_for_ds/blob/main/6_N%EC%B0%A8%EC%9B%90%EB%B0%B0%EC%97%B4%EC%9D%98%EB%B3%91%ED%95%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
#Section6. N차원 배열의 병합
### 배열의 원소를 추가하고 삭제하는 방법과 데이터를 병합하고 분할하는 방법을 다룬다.
---

## 6-1. 배열에 원소 추가 및 삭제

In [ ]:
# 파이썬 리스트에서
lst = [1,2,3,4,5,6,7,8,9]
print(lst)
lst.insert(2,50)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 50, 3, 4, 5, 6, 7, 8, 9]


## insert

In [ ]:
# ndarray에서
import numpy as np
arr = np.arange(1,10)
print(arr)
arr = np.insert(arr,2,50)  # 주의점: arr.insert()는 없다 / arr= 에 재할당 해줘야한다.
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 1  2 50  3  4  5  6  7  8  9]


In [ ]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# axis=0
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=0)
print("---axis=0---\n",arr)

# axis=1
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=1)
print("---axis=1---\n",arr)

# no axis
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50)
print("---no axis---\n",arr)

---axis=0---
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
---axis=1---
 [[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]
---no axis---
 [ 1  2 50  3  4  5  6  7  8  9 10 11 12]


## delete

In [ ]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# axis=0
print(np.delete(arr, 2, axis=0))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# axis=1
print(np.delete(arr, 2, axis=1))

[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [ ]:
# no axis
print(np.delete(arr,2))

[ 1  2  4  5  6  7  8  9 10 11 12]


---
## 6-2. 배열 간의 병합

In [ ]:
import numpy as np
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)
print(arr1,"\n\n",arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


## append

In [ ]:
# axis=0으로 append
print(np.append(arr1,arr2,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
# axis=1로 append
print(np.append(arr1,arr2,axis=1))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
# vstack() => axis=0 / vertically 수직
print(np.vstack((arr1,arr2)))   #주의: 튜플을 인자로 함.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
# hstack() => axis=1 / horizontally 수평
print(np.hstack((arr1,arr2)))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


## concatenate

## ✅ 🚀 `concatenate()` vs `append()` 차이 정리

| 함수 | 역할 | 특징 | `axis` 사용 |
|------|------|------|------|
| `np.concatenate()` | 여러 배열을 연결 | 같은 차원의 배열만 연결 가능 | ✅ 가능 |
| `np.append()` | 요소 추가 | 배열 끝에 요소 추가 가능 (리스트도 추가 가능) | ✅ 가능 (`axis=None` 기본값) |

---

## ✅ 🚀 결론
✔ **여러 배열을 합칠 때** → `concatenate()`  
✔ **배열 끝에 요소 추가할 때** → `append()`  
✔ **배열 차원이 다르면 `append()`가 더 유연함** 🚀

In [ ]:
import numpy as np
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr3 = np.arange(13,19).reshape(2,3)

print(np.concatenate([arr1,arr2,arr3]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print(np.concatenate([arr1,arr2,arr3],axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print(np.concatenate([arr1,arr2,arr3],axis=1))

[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


---
## 6-3. 배열 분할

In [3]:
# 2차원 배열 생성
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# vsplit() => axis=0을 기준으로 분할
new_arr = np.vsplit(arr,3)
print(new_arr)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [9]:
# hsplit() => axis=1을 기준으로 분할
new_arr = np.hsplit(arr,2)
print(new_arr)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [16]:
# 3차원 배열
arr = np.arange(0,4*6*8).reshape(4,6,8)
print(arr)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]]

 [[ 48  49  50  51  52  53  54  55]
  [ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]]

 [[ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]
  [112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]]

 [[144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]
  [168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]]]


In [17]:
arr_vsplit = np.vsplit(arr,2)
print(arr_vsplit)

[array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63],
        [64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87],
        [88, 89, 90, 91, 92, 93, 94, 95]]]), array([[[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143]],

       [[144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167],
        [168, 169, 170, 171, 172, 173,

In [18]:
arr_hsplit = np.hsplit(arr,3)
print(arr_hsplit)

[array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 159]]]), array([[[ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[160, 161, 162, 163, 164, 165, 166, 167],
        [168, 169, 170, 171, 172, 173, 174, 175]]]), array([[[ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91, 