<a href="https://colab.research.google.com/github/hajonghyun/inflearn_Numpy_Basic_for_ds/blob/main/6_N%EC%B0%A8%EC%9B%90%EB%B0%B0%EC%97%B4%EC%9D%98%EB%B3%91%ED%95%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
#Section6. N차원 배열의 병합
### 배열의 원소를 추가하고 삭제하는 방법과 데이터를 병합하고 분할하는 방법을 다룬다.
---

## 6-1. 배열에 원소 추가 및 삭제

In [6]:
# 파이썬 리스트에서
lst = [1,2,3,4,5,6,7,8,9]
print(lst)
lst.insert(2,50)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 50, 3, 4, 5, 6, 7, 8, 9]


## insert

In [11]:
# ndarray에서
import numpy as np
arr = np.arange(1,10)
print(arr)
arr = np.insert(arr,2,50)  # 주의점: arr.insert()는 없다 / arr= 에 재할당 해줘야한다.
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 1  2 50  3  4  5  6  7  8  9]


In [28]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
# axis=0
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=0)
print("---axis=0---\n",arr)

# axis=1
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=1)
print("---axis=1---\n",arr)

# no axis
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50)
print("---no axis---\n",arr)

---axis=0---
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
---axis=1---
 [[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]
---no axis---
 [ 1  2 50  3  4  5  6  7  8  9 10 11 12]


## delete

In [31]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
# axis=0
print(np.delete(arr, 2, axis=0))

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
# axis=1
print(np.delete(arr, 2, axis=1))

[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [38]:
# no axis
print(np.delete(arr,2))

[ 1  2  4  5  6  7  8  9 10 11 12]


---
## 6-2. 배열 간의 병합

In [42]:
import numpy as np
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)
print(arr1,"\n\n",arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


## append

In [43]:
# axis=0으로 append
print(np.append(arr1,arr2,axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [44]:
# axis=1로 append
print(np.append(arr1,arr2,axis=1))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [47]:
# vstack() => axis=0 / vertically 수직
print(np.vstack((arr1,arr2)))   #주의: 튜플을 인자로 함.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [48]:
# hstack() => axis=1 / horizontally 수평
print(np.hstack((arr1,arr2)))

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


## concatenate

## ✅ 🚀 `concatenate()` vs `append()` 차이 정리

| 함수 | 역할 | 특징 | `axis` 사용 |
|------|------|------|------|
| `np.concatenate()` | 여러 배열을 연결 | 같은 차원의 배열만 연결 가능 | ✅ 가능 |
| `np.append()` | 요소 추가 | 배열 끝에 요소 추가 가능 (리스트도 추가 가능) | ✅ 가능 (`axis=None` 기본값) |

---

## ✅ 🚀 결론
✔ **여러 배열을 합칠 때** → `concatenate()`  
✔ **배열 끝에 요소 추가할 때** → `append()`  
✔ **배열 차원이 다르면 `append()`가 더 유연함** 🚀

In [53]:
import numpy as np
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr3 = np.arange(13,19).reshape(2,3)

print(np.concatenate([arr1,arr2,arr3]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [54]:
print(np.concatenate([arr1,arr2,arr3],axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [55]:
print(np.concatenate([arr1,arr2,arr3],axis=1))

[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


---
## 6-3. 배열 분할