<a href="https://colab.research.google.com/github/hajonghyun/inflearn_Numpy_Basic_for_ds/blob/main/my_created_np_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1



# 📌 NumPy 기본 개념 확인 문제

## **1. 배열의 기본 속성 확인**
### **Q1**  
3×4 크기의 `ndarray`를 생성한 후, **(행 개수, 열 개수)**를 출력하라.  

### **Q2**  
위에서 생성한 `ndarray`의 **차원 수**를 출력하라.  

### **Q3**  
위에서 생성한 `ndarray`의 **전체 요소 개수**를 출력하라.  

### **Q4**  
위에서 생성한 `ndarray`의 **데이터 타입**을 출력하라.  

### **Q5**  
1부터 12까지의 정수를 가지는 \(3 \times 4\) 배열을 생성하고, 이를 **0부터 시작하는 인덱스를 사용하여 (2,3) 위치의 요소를 출력하라.**  

---


In [3]:
import numpy as np

arr = np.arange(0,12).reshape(3,4)
#1
print(arr.shape)
#2
print(arr.ndim)
#3
print(arr.size)
#4
print(arr.dtype)
#5
print(arr[2,3])

(3, 4)
2
12
int64
11


## **2. 다양한 배열 생성 방법**
### **Q6**  
모든 요소가 0인 \(2 \times 5\) 크기의 배열을 생성하라.  

### **Q7**  
모든 요소가 1인 \(3 \times 3\) 크기의 배열을 생성하라.  

### **Q8**  
모든 요소가 7인 \(4 \times 2\) 크기의 배열을 생성하라.  

### **Q9**  
0부터 19까지의 숫자가 포함된 1차원 배열을 생성하고, 이를 \(4 \times 5\) 형태의 2차원 배열로 변환하라.  

### **Q10**  
5 이상 10 미만의 난수를 가지는 \(3 \times 3\) 배열을 생성하라.

In [8]:
#6
arr = np.zeros((2,5)) # 두개임에 주의
print(arr)
#7
arr = np.ones((3,3))
print(arr)
#8
arr=np.full((4,2),7)
#9
arr=np.arange(0,20).reshape(4,5)
print(arr)
#10
arr=np.random.uniform(5,10,(3,3))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[6.10586929 7.25183399 9.64694203]
 [9.80268394 5.8145692  6.63355359]
 [9.4621138  9.51575184 9.73073528]]


---
# Section 2

# 📌 NumPy 인덱싱(Indexing) 문제

## **1. 기본 인덱싱**
### **Q1**  
아래 배열이 주어졌을 때, 첫 번째 요소를 출력하라.  

```python
arr = np.array([10, 20, 30, 40, 50])
```

### **Q2**
위 배열에서 마지막 요소를 출력하라.

### **Q3**
아래 2차원 배열에서 첫 번째 행을 출력하라.

```python

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
### **Q4**
위 배열에서 두 번째 행의 모든 요소를 출력하라.

### **Q5**
위 배열에서 세 번째 행의 두 번째 요소(즉, 8)를 출력하라.

In [11]:
#1
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
#2
print(arr[-1])
#3
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0,:])
#4
print(arr2d[1,:])
#5
print(arr2d[2,1])

10
50
[1 2 3]
[4 5 6]
8


## **2. 슬라이싱(Slicing)**
###**Q6**
아래 배열에서 첫 번째부터 세 번째 요소(인덱스 0~2)를 출력하라.

```python
arr = np.array([10, 20, 30, 40, 50])
```

###**Q7**
위 배열에서 마지막 3개의 요소를 출력하라.

###**Q8**
아래 2차원 배열에서 첫 번째 행의 첫 번째와 두 번째 요소만 출력하라.

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
###**Q9**
위 배열에서 마지막 두 행을 출력하라.

###**Q10**
위 배열에서 첫 번째, 두 번째 열만 선택하여 새로운 배열을 만들어라.

In [19]:
#6
arr = np.array([10, 20, 30, 40, 50])
print(arr[0:3])
#7
print(arr[-3:])
#8
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0,:2])
#9
print(arr2d[1:,:])
#10
new_arr = arr2d[:2,:]
print(new_arr)

[10 20 30]
[30 40 50]
[1 2]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


##**3. 불리언 인덱싱(Boolean Indexing)**
###**Q11**
아래 배열에서 5보다 큰 값만 출력하라.

```python
arr = np.array([1, 3, 5, 7, 9, 10, 12])
```
###**Q12**
위 배열에서 짝수만 출력하라.

###**Q13**
아래 2차원 배열에서 10보다 큰 값만 출력하라.

```python
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
```
###**Q14**
위 배열에서 30 이상인 값만 출력하라.

###**Q15**
위 배열에서 20 이상인 값은 True, 그렇지 않은 값은 False로 변환한 마스크 배열을 생성하라.

In [30]:
#11
arr = np.array([1, 3, 5, 7, 9, 10, 12])
print(arr[arr>5])
#12
print(arr[arr%2 == 0])
#13
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
print(arr2d[arr2d>10])
#14
print(arr2d[arr2d>30])
#15
print(arr2d>20)

[ 7  9 10 12]
[10 12]
[15 20 25 30 35 40 45]
[35 40 45]
[[False False False]
 [False  True  True]
 [ True  True  True]]


##**4. 팬시 인덱싱(Fancy Indexing)**
###**Q16**
아래 배열에서 인덱스 0, 2, 4에 해당하는 요소만 출력하라.

```python
arr = np.array([10, 20, 30, 40, 50])
```
###**Q17**
아래 2차원 배열에서 첫 번째와 세 번째 행만 선택하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
###**Q18**💥
아래 배열에서 [2, 1, 0] 순서로 행을 재배열하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
```

###**Q19**
아래 배열에서 특정 열(0번째와 2번째 열)만 선택하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
###**Q20**
아래 배열에서 첫 번째 열과 마지막 열을 선택하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
```

In [40]:
#16
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0,2,4]])
#17
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
new_arr = arr2d[[0,2],:]
print(new_arr)
#18
new_arr = arr2d[[2,1,0],:]
print(new_arr)
#19
new_arr = arr2d[[0,2],:]
print(new_arr)
#20
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
new_arr = arr2d[:,[0,-1]]
print(new_arr)

[10 30 50]
[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [7 8 9]]
[[ 5 15]
 [20 30]
 [35 45]]
