<a href="https://colab.research.google.com/github/hajonghyun/inflearn_Numpy_Basic_for_ds/blob/main/%EB%82%B4%EA%B0%80%EB%A7%8C%EB%93%A0np%EB%AC%B8%EC%A0%9Csection1~6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1



# 📌 NumPy 기본 개념 확인 문제

## **1. 배열의 기본 속성 확인**
### **Q1**  
3×4 크기의 `ndarray`를 생성한 후, **(행 개수, 열 개수)**를 출력하라.  

### **Q2**  
위에서 생성한 `ndarray`의 **차원 수**를 출력하라.  

### **Q3**  
위에서 생성한 `ndarray`의 **전체 요소 개수**를 출력하라.  

### **Q4**  
위에서 생성한 `ndarray`의 **데이터 타입**을 출력하라.  

### **Q5**  
1부터 12까지의 정수를 가지는 \(3 \times 4\) 배열을 생성하고, 이를 **0부터 시작하는 인덱스를 사용하여 (2,3) 위치의 요소를 출력하라.**  

---


In [ ]:
import numpy as np

arr = np.arange(0,12).reshape(3,4)
#1
print(arr.shape)
#2
print(arr.ndim)
#3
print(arr.size)
#4
print(arr.dtype)
#5
print(arr[2,3])

(3, 4)
2
12
int64
11


## **2. 다양한 배열 생성 방법**
### **Q6**  
모든 요소가 0인 \(2 \times 5\) 크기의 배열을 생성하라.  

### **Q7**  
모든 요소가 1인 \(3 \times 3\) 크기의 배열을 생성하라.  

### **Q8**  
모든 요소가 7인 \(4 \times 2\) 크기의 배열을 생성하라.  

### **Q9**  
0부터 19까지의 숫자가 포함된 1차원 배열을 생성하고, 이를 \(4 \times 5\) 형태의 2차원 배열로 변환하라.  

### **Q10**  
5 이상 10 미만의 난수를 가지는 \(3 \times 3\) 배열을 생성하라.

In [ ]:
#6
arr = np.zeros((2,5)) # 두개임에 주의
print(arr)
#7
arr = np.ones((3,3))
print(arr)
#8
arr=np.full((4,2),7)
#9
arr=np.arange(0,20).reshape(4,5)
print(arr)
#10
arr=np.random.uniform(5,10,(3,3))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[6.10586929 7.25183399 9.64694203]
 [9.80268394 5.8145692  6.63355359]
 [9.4621138  9.51575184 9.73073528]]


---
# Section 2

# 📌 NumPy 인덱싱(Indexing) 문제

## **1. 기본 인덱싱**
### **Q1**  
아래 배열이 주어졌을 때, 첫 번째 요소를 출력하라.  

```python
arr = np.array([10, 20, 30, 40, 50])
```

### **Q2**
위 배열에서 마지막 요소를 출력하라.

### **Q3**
아래 2차원 배열에서 첫 번째 행을 출력하라.

```python

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
### **Q4**
위 배열에서 두 번째 행의 모든 요소를 출력하라.

### **Q5**
위 배열에서 세 번째 행의 두 번째 요소(즉, 8)를 출력하라.

In [ ]:
#1
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
#2
print(arr[-1])
#3
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0,:])
#4
print(arr2d[1,:])
#5
print(arr2d[2,1])

10
50
[1 2 3]
[4 5 6]
8


## **2. 슬라이싱(Slicing)**
###**Q6**
아래 배열에서 첫 번째부터 세 번째 요소(인덱스 0~2)를 출력하라.

```python
arr = np.array([10, 20, 30, 40, 50])
```

###**Q7**
위 배열에서 마지막 3개의 요소를 출력하라.

###**Q8**
아래 2차원 배열에서 첫 번째 행의 첫 번째와 두 번째 요소만 출력하라.

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
###**Q9**
위 배열에서 마지막 두 행을 출력하라.

###**Q10**
위 배열에서 첫 번째, 두 번째 열만 선택하여 새로운 배열을 만들어라.

In [ ]:
#6
arr = np.array([10, 20, 30, 40, 50])
print(arr[0:3])
#7
print(arr[-3:])
#8
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(arr2d[0,:2])
#9
print(arr2d[1:,:])
#10
new_arr = arr2d[:2,:]
print(new_arr)

[10 20 30]
[30 40 50]
[1 2]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


##**3. 불리언 인덱싱(Boolean Indexing)**
###**Q11**
아래 배열에서 5보다 큰 값만 출력하라.

```python
arr = np.array([1, 3, 5, 7, 9, 10, 12])
```
###**Q12**
위 배열에서 짝수만 출력하라.

###**Q13**
아래 2차원 배열에서 10보다 큰 값만 출력하라.

```python
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
```
###**Q14**
위 배열에서 30 이상인 값만 출력하라.

###**Q15**
위 배열에서 20 이상인 값은 True, 그렇지 않은 값은 False로 변환한 마스크 배열을 생성하라.

In [ ]:
#11
arr = np.array([1, 3, 5, 7, 9, 10, 12])
print(arr[arr>5])
#12
print(arr[arr%2 == 0])
#13
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
print(arr2d[arr2d>10])
#14
print(arr2d[arr2d>30])
#15
print(arr2d>20)

[ 7  9 10 12]
[10 12]
[15 20 25 30 35 40 45]
[35 40 45]
[[False False False]
 [False  True  True]
 [ True  True  True]]


##**4. 팬시 인덱싱(Fancy Indexing)**
###**Q16**
아래 배열에서 인덱스 0, 2, 4에 해당하는 요소만 출력하라.

```python
arr = np.array([10, 20, 30, 40, 50])
```
###**Q17**
아래 2차원 배열에서 첫 번째와 세 번째 행만 선택하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
###**Q18**💥
아래 배열에서 [2, 1, 0] 순서로 행을 재배열하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
```

###**Q19**
아래 배열에서 특정 열(0번째와 2번째 열)만 선택하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```
###**Q20**
아래 배열에서 첫 번째 열과 마지막 열을 선택하여 새로운 배열을 만들어라.

```python
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
```

In [ ]:
#16
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0,2,4]])
#17
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
new_arr = arr2d[[0,2],:]
print(new_arr)
#18
new_arr = arr2d[[2,1,0],:]
print(new_arr)
#19
new_arr = arr2d[[0,2],:]
print(new_arr)
#20
arr2d = np.array([[5, 10, 15],
                  [20, 25, 30],
                  [35, 40, 45]])
new_arr = arr2d[:,[0,-1]]
print(new_arr)

[10 30 50]
[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2 3]
 [7 8 9]]
[[ 5 15]
 [20 30]
 [35 45]]


# Section 3: N차원 배열 연산법 - 학습 확인 문제

## 문제 1: 배열 생성 및 기본 연산

1. 1부터 9까지의 정수를 요소로 갖는 1차원 NumPy 배열 `a`를 생성하시오.
2. 배열 `a`의 요소들을 3x3 형태의 2차원 배열로 변형하시오.
3. 배열 `a`의 모든 요소에 2를 더한 결과를 출력하시오.
4. 배열 `a`의 모든 요소를 2로 나눈 결과를 출력하시오.

In [ ]:
#1
import numpy as np
a = np.arange(1,10)
print(a)
#2
a=a.reshape(3,3)
print(a)
#3
print(a+2)
#4
print(a/2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


## 문제 2: 배열 간 연산

1. 3x3 형태의 배열 `b`를 생성하되, 모든 요소가 1인 배열로 만드시오.
2. 배열 `a`와 배열 `b`를 더한 결과를 출력하시오.
3. 배열 `a`와 배열 `b`를 요소별로 곱한 결과를 출력하시오.
4. 배열 `a`의 각 행의 합을 계산하시오.
5. 배열 `a`의 각 열의 합을 계산하시오.

흔히 혼동되는 표현이라 명확히 할 필요가 있습니다.
NumPy에서는 일반적으로 다음과 같이 표현합니다.

- 배열의 각 행의 합을 구하시오:
→ 각각의 행 안에 있는 요소들의 합을 구하라는 의미입니다.
즉, 행별로 내부 요소끼리 합산하는 것입니다.

- 배열의 각 열의 합을 구하시오:
→ 각각의 열 안에 있는 요소들의 합을 구하라는 의미입니다.
즉, 열별로 내부 요소끼리 합산하는 것입니다.

In [ ]:
#1
print(a)
b = np.ones((3,3))
print(b)
#2
print(a+b)
#3
print(a@b)
print(a.dot(b))
#4
print(np.sum(a,axis=1))
#5
print(np.sum(a,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]
[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]
[ 6 15 24]
[12 15 18]


## 문제 3: 브로드캐스팅

1. 배열 `a`의 각 행에 배열 `[1, 0, 1]`을 더한 결과를 출력하시오.
2. 배열 `a`의 각 열에 배열 `[1, 2, 3]`을 더한 결과를 출력하시오.
3. 배열 `a`의 각 요소에 10을 곱한 결과를 출력하시오.

In [ ]:
print(a)
#1
print(a+np.array([1,0,1]))
#2
print(a+np.array([[1],
                  [2],
                  [3]]))
#3
print(a*10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


## 문제 4: 집계 함수

1. 배열 `a`의 모든 요소의 합을 계산하시오.
2. 배열 `a`의 모든 요소의 평균을 계산하시오.
3. 배열 `a`의 모든 요소의 최댓값과 최솟값을 구하시오.
4. 배열 `a`의 각 행의 표준편차를 계산하시오.

In [ ]:
print(a)
#1
print(a.sum())
#2
print(a.mean())
#3
print(a.max())
print(a.min())
#4
print(a.std())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
5.0
9
1
2.581988897471611


## 문제 5: 배열 인덱싱 및 슬라이싱

1. 배열 `a`에서 첫 번째 행을 추출하시오.
2. 배열 `a`에서 두 번째 열을 추출하시오.
3. 배열 `a`에서 첫 번째 행과 두 번째 행을 추출하시오.
4. 배열 `a`에서 두 번째 열과 세 번째 열을 추출하시오.
5. 배열 `a`에서 홀수 번째 행을 추출하시오.

In [ ]:
print(a)
#1
print(a[0])
#2
print(a[:,1])
print(a[:,[1]])
#3
print(a[[0,1],:])
#4
print(a[:,[1,2]])
#5
print(a[[0,2],:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[2 5 8]
[[2]
 [5]
 [8]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]
 [7 8 9]]


## 문제 6: 불리언 인덱싱

1. 배열 `a`에서 5보다 큰 요소들만 추출하시오.
2. 배열 `a`에서 짝수인 요소들만 추출하시오.
3. 배열 `a`에서 3의 배수인 요소들만 추출하시오.


In [ ]:
print(a)
#1
print(a[a>5])
#2
print(a[a%2==0])
#3
print(a[a%3==0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[6 7 8 9]
[2 4 6 8]
[3 6 9]


# Section 4

문제 1: 1차원 배열의 정렬
다음과 같은 1차원 Numpy 배열이 있습니다:

```python
import numpy as np
arr = np.array([5, 2, 9, 1, 7])
```
1. 이 배열을 오름차순으로 정렬하세요.
2. 이 배열을 내림차순으로 정렬하세요.

In [ ]:
import numpy as np
arr = np.array([5, 2, 9, 1, 7])
#1
arr = np.sort(arr)
print(arr)
#2
arr = np.sort(arr)[::-1]
print(arr)

[1 2 5 7 9]
[9 7 5 2 1]


##문제 2: 2차원 배열의 행별 정렬

다음과 같은 2차원 Numpy 배열이 있습니다:

```python
import numpy as np

arr = np.array([[3, 1, 2], [9, 7, 8], [6, 5, 4]])
```
(1) 각 행을 오름차순으로 정렬하세요.

💥(2) 각 행을 내림차순으로 정렬하세요.

In [ ]:
import numpy as np

arr = np.array([[3, 1, 2], [9, 7, 8], [6, 5, 4]])
print(arr)
#1
arr = np.sort(arr,axis=1)
print(arr)
#2
arr = np.sort(arr,axis=1)[:,::-1]
print(arr)

[[3 1 2]
 [9 7 8]
 [6 5 4]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[3 2 1]
 [9 8 7]
 [6 5 4]]


(1) 각 열을 오름차순으로 정렬하세요.

(2) 각 열을 내림차순으로 정렬하세요.

In [ ]:
arr = np.array([[3, 1, 2], [9, 7, 8], [6, 5, 4]])

#1
arr = np.sort(arr,axis=0)
print(arr)
#2
arr = np.sort(arr,axis=0)[::-1,:]
print(arr)

[[3 1 2]
 [6 5 4]
 [9 7 8]]
[[9 7 8]
 [6 5 4]
 [3 1 2]]


##문제 4: 다차원 배열에서 argsort 사용

다음과 같은 2차원 Numpy 배열이 있습니다:

```python
import numpy as np

arr = np.array([[10, 15, 12], [9, 8, 13], [14, 11, 7]])
```
(1) 각 행의 요소들을 오름차순으로 정렬했을 때의 인덱스를 반환하세요.

(2) 각 열의 요소들을 오름차순으로 정렬했을 때의 인덱스를 반환하세요.

In [ ]:
import numpy as np

arr = np.array([[10, 15, 12], [9, 8, 13], [14, 11, 7]])
print(arr)
#1
print(np.argsort(arr,axis=1))
#2
print(np.argsort(arr,axis=0))

[[10 15 12]
 [ 9  8 13]
 [14 11  7]]
[[0 2 1]
 [1 0 2]
 [2 1 0]]
[[1 1 2]
 [0 2 0]
 [2 0 1]]


##문제 5: 다차원 배열의 부분 정렬
다음과 같은 3차원 Numpy 배열이 있습니다:

```python
import numpy as np

arr = np.array([[[1, 4, 2], [3, 6, 5]], [[9, 7, 8], [12, 10, 11]]])
```
(1) 배열의 마지막 축(axis=-1)을 따라 오름차순으로 정렬하세요.

(2) 배열의 마지막 축(axis=-1)을 따라  내림차순으로 정렬하세요.

In [ ]:
import numpy as np

arr = np.array([[[1, 4, 2],
                 [3, 6, 5]],
                [[9, 7, 8],
                 [12, 10, 11]]])
print(arr)
print('------------------')
#1
print(np.sort(arr,axis=-1))
print('------------------')
#2
print(np.sort(arr,axis=-1))
print('------------------')
#3
print(np.sort(arr,axis=-1)[:,:,::-1])
print('------------------')

[[[ 1  4  2]
  [ 3  6  5]]

 [[ 9  7  8]
  [12 10 11]]]
------------------
[[[ 1  2  4]
  [ 3  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------------------
[[[ 1  2  4]
  [ 3  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------------------
[[[ 4  2  1]
  [ 6  5  3]]

 [[ 9  8  7]
  [12 11 10]]]
------------------


# Section 5

###Q1
아래 1차원 배열을 (3, 4) 형태의 2차원 배열로 변경하여 출력하라.

```python
arr = np.arange(12)
```
### Q2
아래 1차원 배열을 (2, 3, 2) 형태의 3차원 배열로 변경하여 출력하라.

```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
```
###Q3
아래 배열을 reshape을 사용하여 (4, -1) 형태의 배열로 변경하라. 이때 -1을 사용하는 이유를 설명하라.

```python
arr = np.arange(20)
```
###Q4
아래의 3차원 배열을 1차원 배열로 평탄화(flatten)하여 출력하라.

```python
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
```
###Q5
아래 배열을 평탄화 할 때 flatten() 메소드와 ravel() 메소드의 차이점을 설명하고, 각각의 메소드를 사용하여 평탄화된 배열을 출력하라.

```python
arr2d = np.array([[10, 20, 30], [40, 50, 60]])
```

In [ ]:
arr = np.arange(12)
#1
print(arr.reshape(3,4))
#2
print(arr.reshape(2,3,2))
#3
arr = np.arange(20)
print(arr.reshape(4,-1))
#4
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print(arr3d.reshape(-1))
print(arr3d.ravel())
#5
arr2d = np.array([[10, 20, 30], [40, 50, 60]])

# flatten과 ravel 적용
flat_arr = arr2d.flatten()
ravel_arr = arr2d.ravel()

print("원본 arr2d:\n", arr2d)
print("flatten 결과:", flat_arr)
print("ravel 결과:", ravel_arr)

# 원본 배열 arr2d를 수정
arr2d[0, 0] = 99
print("\n원본 수정 후:")
print("arr2d:\n", arr2d)
print("flatten 결과:", flat_arr)  # 변화 없음
print("ravel 결과:", ravel_arr)   # 변화 있음

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
원본 arr2d:
 [[10 20 30]
 [40 50 60]]
flatten 결과: [10 20 30 40 50 60]
ravel 결과: [10 20 30 40 50 60]

원본 수정 후:
arr2d:
 [[99 20 30]
 [40 50 60]]
flatten 결과: [10 20 30 40 50 60]
ravel 결과: [99 20 30 40 50 60]


## **Section 6. N차원 배열의 병합(concatenate, vstack, hstack)**

### **Q1**
아래 두 배열을 **세로 방향(axis=0)** 으로 연결(concatenate)하여 하나의 배열을 생성하고 출력하라.

```python
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
```

### **Q2**
위의 두 배열을 가로 방향(axis=1) 으로 연결(concatenate)하여 하나의 배열을 생성하고 출력하라.

### **Q3**
np.vstack()과 np.hstack()의 차이점을 설명하고, 아래 배열을 각각 vstack과 hstack을 이용하여 병합한 결과를 출력하라.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

### **Q4**
아래의 1차원 배열 3개를 세로 방향으로 연결하여 2차원 배열로 만든 후 출력하라. (단, vstack()을 사용하라.)

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
```

### **Q5**
아래의 2차원 배열 두 개를 hstack()을 사용하여 연결한 후, 새로 만들어진 배열의 shape를 출력하라.

```python
arr1 = np.ones((3, 2))
arr2 = np.zeros((3, 3))
```

### **Q6**
아래 두 배열을 연결할 때, 왜 axis=0 으로 연결하면 오류가 나는지 설명하고, 이를 수정하여 연결한 결과를 출력하라.

```python
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
```

### **Q7**
아래 배열을 열(column) 기준으로 3개로 나눈 후(split), 나누어진 각각의 배열을 출력하라.

```python
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]])
```

### **Q8**
아래 배열을 행(row) 기준으로 2개로 나눈 후(split), 각각의 배열을 출력하라.

```python
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])
```

### **Q9**
아래 배열을 열 기준으로 np.split()이 아니라 np.hsplit()을 사용하여 두 배열로 나눈 뒤, 각각의 배열을 출력하라. 그리고 np.split()과 np.hsplit()의 차이점을 간략히 설명하라.

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
```

### **Q10**
다음의 3차원 배열 두 개를 axis=2 축 방향으로 연결(concatenate)하여 하나의 배열로 만든 뒤, 결과 배열의 shape를 출력하라.

```python
arr1 = np.ones((2, 2, 2))
arr2 = np.zeros((2, 2, 3))
```


In [ ]:
#1
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])
arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)
#2
arr4 = np.concatenate((arr1,arr2),axis=1)
print(arr4)
#3
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
#4
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr4 = np.vstack((arr1,arr2,arr3))
print(arr4)
#5
arr1 = np.ones((3,2))
arr2 = np.zeros((3,3))
arr3 = np.hstack((arr1,arr2))
print(arr3,arr3.shape)
#6
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
arr3 = np.hstack((arr1,arr2))
print(arr3)
#7
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12]])
arr2 = np.split(arr,3,axis=1)
print(arr2)
arr2 = np.hsplit(arr,3) ## 주의
print(arr2)
#8
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                [100, 110, 120]])
arr2 = np.split(arr,2,axis=0)
print(arr2)
arr2 = np.vsplit(arr,2)
print(arr2)
#9
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
arr1,arr2 = np.hsplit(arr,2)
print("arr1: ",arr1,"\narr2:",arr2)
#10
arr1 = np.ones((2, 2, 2))
arr2 = np.zeros((2, 2, 3))
arr3 = np.concatenate((arr1,arr2),axis=2)
print(arr3)
print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]] (3, 5)
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]
[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]
arr1:  [[1 2]
 [5 6]] 
arr2: [[3 4]
 [7 8]]
[[[1. 1. 0. 0. 0.]
  [1. 1. 0. 0. 0.]]

 [[1. 1. 0. 0. 0.]
  [1. 1. 0. 0. 0.]]]
(2, 2, 5)
